Feature/validator attrname
fabbricadigitale/scimd pull request #19
Opened 2017-11-23 13:55 UTC by samechelon

2017-11-23 17:46 UTC, leogr requested changes
@leodido 
Special case for `$ref` is missing!

2017-11-24 10:41 UTC, leodido commented on validation/attrname.go
> +var attrName = func(fl validator.FieldLevel) bool {
Ok but please notice this have to be a contextual validator.

It have to check the attribute name format **only** when the attribute type is not equal to "reference".

2017-11-24 10:41 UTC, leodido commented on validation/attrname_test.go
> +	errors := Validator.Struct(x)
Please use `Validator.Var(...)` ...

2017-11-27 17:14 UTC, leogr approved these changes

2017-11-27 17:14 UTC, merged